# Generated by Django 4.0.5 on 2023-01-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('rate', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('time', models.IntegerField()),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, upload_to='foods/%Y/%m/%d')),
                ('type_food', models.CharField(choices=[('drinks', 'نوشیدنی'), ('lunch', 'نهار'), ('dinner', 'شام')], default='drinks', max_length=20)),
            ],
        ),
    ]
