# Generated by Django 4.0.5 on 2023-01-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'picture',
                'verbose_name_plural': 'gallery',
            },
        ),
    ]
